#----------------------------------------------------------------------
# This file was generated by C:\Python27\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

AppIcon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAANtJ"
    "REFUWIXNlkESgzAIRSX2Vj2aXdqj9Vg13cjU/koBiwNvF0mc4QFRojYOW/ry7MMO1EbaxqW1"
    "l3bkUCQXKYAZWunL4+d+atcPU3UNeDNnMMP3+/bN1DUgdXVU9zP5BrRM+rTG775MueZaT+Qb"
    "wMytNbXuw+7Hdb4BfKDV3NoTXHtp/jmeboC+voaT7QaMmop6BhjJhDdzjboGmKM3oZX6Bpib"
    "8H8wrzcix7U1km5A/B+QmP/8/uP5dANhPYD7pOdIuoGwHtCmQDpf14C1lt6pwPPpBsxTcBbp"
    "Bl7cLYSebvlRfQAAAABJRU5ErkJggg==")

